### ISSUE TITLE
MySQL configuration

### ISSUE THREAD

**Issue by fyqdcj123** [PufferPanel/PufferPanel#1117]
How should I modify the database type to MySQL? I can't find the configuration file on the document before installation

**Comment by thecmdradama** [comment]
Hi @fyqdcj123,
You'll need to install the panel first then update the config file as per the docs.  
https://docs.pufferpanel.com/en/latest/guides/database.html
Also, for future reference, you will likely get better support over at the PufferPanel Discord https://discord.gg/v8dz49e

**Comment by fyqdcj123** [comment]
After installing the panel, I modify the configuration file and access the web. The server displays 502

**Comment by thecmdradama** [comment]
Please paste your current config?

**Comment by fyqdcj123** [comment]
```
{
  "logs": "/var/log/pufferpanel",
  "panel": {
    "database": {
      "dialect": "mysql",
      "url": "game:game@tcp(47.100.92.203:3306)/pufferpanel"
    },
    "web": {
      "files": "/var/www/pufferpanel"
    }
  },
  "daemon": {
    "data": {
      "cache": "/var/lib/pufferpanel/cache",
      "servers": "/var/lib/pufferpanel/servers"
    }
  }
}
```

**Comment by thecmdradama** [comment]
Config looks good. When you get the 502, what do you see in the browser console logs. 
Also, what do you see in the latest log in /var/log/pufferpanel

**Comment by fyqdcj123** [comment]
```
Bad Gateway, is PufferPanel running? (502)

Endpoint: get /api/config

Authorization Header: Bearer 



Stacktrace: Error: Request failed with status code 502
    at t.exports (http://198.144.183.241:8080/js/chunk-vendors.105dfe0b.js:7:70541)
    at t.exports (http://198.144.183.241:8080/js/chunk-vendors.105dfe0b.js:20:56819)
    at XMLHttpRequest.p.onreadystatechange (http://198.144.183.241:8080/js/chunk-vendors.105dfe0b.js:37:46377)
```
The above are web tips

**Comment by fyqdcj123** [comment]
```
Failed to load resource: the server responded with a status of 502 (Bad Gateway)
app.2a38c1c2.js:1 ERROR Error: Request failed with status code 502
    at t.exports (chunk-vendors.105dfe0b.js:7:70541)
    at t.exports (chunk-vendors.105dfe0b.js:20:56819)
    at XMLHttpRequest.p.onreadystatechange (chunk-vendors.105dfe0b.js:37:46377)
handleError @ app.2a38c1c2.js:1
login:1 Failed to load resource: the server responded with a status of 502 (Bad Gateway)
manifest.json:1 Failed to load resource: the server responded with a status of 502 (Bad Gateway)
```
The above is the console log

**Comment by thecmdradama** [comment]
and in the logs in /var/log/pufferpanel? also I suggest obfuscating your public IP.

**Comment by fyqdcj123** [comment]
```
2022/01/27 08:05:13 /home/runner/work/PufferPanel/PufferPanel/database/migrate.go:16 Error 1091: Can't DROP 'uix_servers_name'; check that column/key exists
[209.343ms] [rows:0] DROP INDEX `uix_servers_name` ON `servers`
[DEBUG] 2022/01/27 08:05:13 removing unique key for server.name with err `Error 1091: Can't DROP 'uix_servers_name'; check that column/key exists`
```

**Comment by fyqdcj123** [comment]
[2022-01-27T08-12-45.log](https://github.com/PufferPanel/PufferPanel/files/7950679/2022-01-27T08-12-45.log)

**Comment by thecmdradama** [comment]
I'm assuming you have set up access to the database correctly... As this is a brand new setup just delete the sqilte database and restart the panel.

**Comment by fyqdcj123** [comment]
When I delete the sqlte database and restart it, it still can't be solved

**Comment by LexFuturorum** [comment]
did you add an admin user with the new database yet?

**Comment by fyqdcj123** [comment]
I use admin in the new database

**Comment by fyqdcj123** [comment]
> 

yes

**Comment by fyqdcj123** [comment]
> How to use MySQL during installation by modifying the configuration file

**Comment by LexFuturorum** [comment]
modify the config before you first fire it up or add an admin user
