### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference goroutine 1

### ISSUE THREAD

**Issue by Kame03** [PufferPanel/PufferPanel#1119]
Hello whenever I try to install the latest release of this panel I get this error, but the panel worked fine on a previous release.
I'm running gentoo.

`[ERROR] 2022/01/30 15:32:56 runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.17.3/x64/src/runtime/debug/stack.go:24 +0x88
main.main.func1()
        /home/runner/work/PufferPanel/PufferPanel/cmd/main.go:35 +0x48
panic({0x1081be0, 0x1b588c0})
        /opt/hostedtoolcache/go/1.17.3/x64/src/runtime/panic.go:1038 +0x224
main.daemon(0x4000098600)
        /home/runner/work/PufferPanel/PufferPanel/cmd/run.go:235 +0x4f0
main.internalRun(0x4000098600, 0x4000098720)
        /home/runner/work/PufferPanel/PufferPanel/cmd/run.go:108 +0x4dc
main.executeRun(0x1b69b20, {0x2518b08, 0x0, 0x0})
        /home/runner/work/PufferPanel/PufferPanel/cmd/run.go:54 +0x60
github.com/spf13/cobra.(*Command).execute(0x1b69b20, {0x2518b08, 0x0, 0x0})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x650
github.com/spf13/cobra.(*Command).ExecuteC(0x1b698a0)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x364
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.Execute()
        /home/runner/work/PufferPanel/PufferPanel/cmd/main.go:77 +0x78
main.main()
        /home/runner/work/PufferPanel/PufferPanel/cmd/main.go:42 +0x84

`

**Comment by MajliTech** [comment]
? How's that closed as completed? Here's my log:
```log
Jun 16 15:00:47 serwerintranet pufferpanel[1652264]: [GIN] 2023/06/16 - 15:00:47 | 500 |   91.174064ms |   192.168.12.51 | POST     "/auth/login"
Jun 16 15:01:22 serwerintranet pufferpanel[1652264]: [ERROR] 2023/06/16 15:01:22 Internal error on token service: open private.pem: permission denied
Jun 16 15:01:22 serwerintranet pufferpanel[1652264]: [ERROR] 2023/06/16 15:01:22 runtime error: invalid memory address or nil pointer dereference
Jun 16 15:01:22 serwerintranet pufferpanel[1652264]: [ERROR] 2023/06/16 15:01:22 Error handling route
```

**Comment by OptimusGREEN** [comment]
I'm having this issue too and also see that this looks like it shouldn't have been closed?

**Comment by LordRalex** [comment]
Rather than claiming you have the same issue, post the full log into our Discord.

**Comment by OptimusGREEN** [comment]
Rather than being rude to people in most issues I've seen you comment on, why not deal with issues in the issues section instead of redirecting to a chat platform that frankly isn't suitable for the purpose. 

I'll just use another platform.

**Comment by LordRalex** [comment]
I am being blunt. I need a full log to assist, and neither you nor the one who had the "same error" provided it. I can already tell the one above you is not having the same error. So, I can assume the same for you.

**Comment by LordRalex** [comment]
Also, this stacktrace does not apply for the latest of v2 and v3, so regardless, the "issue" is closed. Any error you see is not the same as this one.
