### ISSUE TITLE
Erreur Start GSD 

### ISSUE THREAD

**Issue by MrPalamen** [PufferPanel/PufferPanel#523]
fs.js:439
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory 'https.key'
    at Object.fs.openSync (fs.js:439:18)
    at Object.fs.readFileSync (fs.js:290:15)
    at Object.<anonymous> (/srv/gsd/interfaces/console.js:5:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/srv/gsd/gsd.js:13:1)

**Comment by DaneEveritt** [comment]
`Error: ENOENT, no such file or directory 'https.key'`

Please follow the instructions for how to setup GSD.

**Comment by MrPalamen** [comment]
openssl req -x509 -days 365 -newkey rsa:4096 -keyout https.key -out https.pem -nodes

**Comment by DaneEveritt** [comment]
Yes, you need to run that command inside the `/srv/gsd` directory.

**Comment by MrPalamen** [comment]
"Une erreur s'est produite avec cette requête AJAX. (timeout)" au démarage du serveur

**Comment by DaneEveritt** [comment]
You're not following the documentation at all. You don't use PufferPanel to execute those commands. You need to SSH into your server and execute them.
