### ISSUE TITLE
session.lock no permission

### ISSUE THREAD

**Issue by checkplys** [PufferPanel/PufferPanel#671]
I upload my world to pufferpanel, and when I turn on the server I get this:

`
[19:28:56 INFO]: **** Beginning UUID conversion, this may take A LONG time ****

[19:28:56 INFO]: Preparing level "world"
[19:28:56 WARN]: java.io.FileNotFoundException: ./world/session.lock (Permission denied)
[19:28:56 WARN]: 	at java.io.FileOutputStream.open(Native Method)
[19:28:56 WARN]: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
[19:28:56 WARN]: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:171)
[19:28:56 WARN]: 	at net.minecraft.server.v1_8_R3.WorldNBTStorage.h(WorldNBTStorage.java:47)
[19:28:56 WARN]: 	at net.minecraft.server.v1_8_R3.WorldNBTStorage.<init>(WorldNBTStorage.java:41)
[19:28:56 WARN]: 	at net.minecraft.server.v1_8_R3.ServerNBTManager.<init>(SourceFile:19)
[19:28:56 WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:261)
[19:28:56 WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263)
[19:28:56 WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)
[19:28:56 WARN]: 	at java.lang.Thread.run(Thread.java:745)
[19:28:56 ERROR]: Encountered an unexpected exception
java.lang.RuntimeException: Failed to check session lock for world located at ./world, aborting. Stop the server and delete the session.lock in this world to prevent further issues.	at net.minecraft.server.v1_8_R3.WorldNBTStorage.h(WorldNBTStorage.java:57) ~[minecraft_server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.WorldNBTStorage.<init>(WorldNBTStorage.java:41) ~[minecraft_server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.ServerNBTManager.<init>(SourceFile:19) ~[minecraft_server.jar:git-Spigot-db6de12-18fbb24]	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:261) ~[minecraft_server.jar:git-Spigot-db6de12-18fbb24]	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) ~[minecraft_server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [minecraft_server.jar:git-Spigot-db6de12-18fbb24]	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_95]
[19:28:56 ERROR]: This crash report has been saved to: /home/pp-lobby_yr0qkb/public/./crash-reports/crash-2016-02-07_19.28.56-server.txt
´

I alredy deletede session.lock, it doesn't exists, but I steel have the error.

**Comment by checkplys** [comment]
I found that I need to run with sudo, if it's right, how I can do that?

**Comment by LordRalex** [comment]
You should not run it as sudo, nor should you be uploading files as root.
Use the SFTP creds from the panel to upload to servers.

**Comment by checkplys** [comment]
I can't, every time I just get "The server don't connecd by SFTP, bit seems working with FTP." or something line that

**Comment by checkplys** [comment]
Ok, now I can connect with the main credentials, it's possible to edit the files with they? Where are server files stored (path)?

**Comment by checkplys** [comment]
All Solved :D
