### ISSUE TITLE
BungeeCord Instance Issue/Bug

### ISSUE THREAD

**Issue by PeterEstephan** [PufferPanel/PufferPanel#685]
Upon making my BungeeCord instance I found that after a while when I left it off and tried to turn it back on I got this error: 

`[2016-04-04 22:14:12] [INFO] Error: ENOENT: no such file or directory, open '/home/pp-bungee_yn7v7/public/logs/latest.log'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Scales.logContents (/srv/scales/lib/process.js:588:20)
    at Server.<anonymous> (/srv/scales/lib/interfaces/restify.js:347:21)
    at next (/srv/scales/node_modules/restify/lib/server.js:906:30)
    at f (/srv/scales/node_modules/restify/node_modules/once/once.js:17:25)
    at Server.restifyCORSSimple (/srv/scales/node_modules/restify/lib/plugins/cors.js:104:13)
    at next (/srv/scales/node_modules/restify/lib/server.js:906:30)
    at f (/srv/scales/node_modules/restify/node_modules/once/once.js:17:25)
[2016-04-04 22:18:14] [INFO] Error: ENOENT: no such file or directory, open '/home/pp-bungee_yn7v7/public/logs/latest.log'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Scales.logContents (/srv/scales/lib/process.js:588:20)
    at Server.<anonymous> (/srv/scales/lib/interfaces/restify.js:347:21)
    at next (/srv/scales/node_modules/restify/lib/server.js:906:30)
    at f (/srv/scales/node_modules/restify/node_modules/once/once.js:17:25)
    at Server.restifyCORSSimple (/srv/scales/node_modules/restify/lib/plugins/cors.js:104:13)
    at next (/srv/scales/node_modules/restify/lib/server.js:906:30)
    at f (/srv/scales/node_modules/restify/node_modules/once/once.js:17:25)
[`

Thanks.

**Comment by puffrfish** [comment]
Please open a thread on our [community forums](https://community.pufferpanel.com) and include the contents of /srv/scales/logs/proc.log. Thanks.
