### ISSUE TITLE
"Unknown Error" when creating server

### ISSUE THREAD

**Issue by nikhiljha** [PufferPanel/PufferPanel#827]
The WebUI says that, but this was what is in my journalctl.

```
Jun 28 23:00:11 mercury pufferd[21561]: [23:00:11] [ERROR] Error handling route
Jun 28 23:00:11 mercury pufferd[21561]: interface conversion: interface {} is nil, not bool
Jun 28 23:00:11 mercury pufferd[21561]: goroutine 33 [running]:
Jun 28 23:00:11 mercury pufferd[21561]: runtime/debug.Stack(0xc4201f71d0, 0xb1ed00, 0xc4201c2d40)
Jun 28 23:00:11 mercury pufferd[21561]:         /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
Jun 28 23:00:11 mercury pufferd[21561]: github.com/pufferpanel/pufferd/vendor/github.com/pufferpanel/apufferi/http/handler.Recovery.func1.1(0xc4200ea2c0)
Jun 28 23:00:11 mercury pufferd[21561]:         /home/teamcity/buildAgent/work/8c94c4c54a5058d8/src/github.com/pufferpanel/pufferd/vendor/github.com/pufferpanel/apufferi/http/handler/errorlogging.go:16 +0x19d
Jun 28 23:00:11 mercury pufferd[21561]: panic(0xb1ed00, 0xc4201c2d40)
Jun 28 23:00:11 mercury pufferd[21561]:         /usr/local/go/src/runtime/panic.go:505 +0x229
Jun 28 23:00:11 mercury pufferd[21561]: github.com/pufferpanel/pufferd/httphandlers.validateToken(0xc4203ff4d7, 0x20, 0xc4200ea2c0, 0x0)
Jun 28 23:00:11 mercury pufferd[21561]:         /home/teamcity/buildAgent/work/8c94c4c54a5058d8/src/github.com/pufferpanel/pufferd/httphandlers/oauth2.go:169 +0x1086
Jun 28 23:00:11 mercury pufferd[21561]: github.com/pufferpanel/pufferd/httphandlers.OAuth2Handler.func1(0xc4200ea2c0)
Jun 28 23:00:11 mercury pufferd[21561]:         /home/teamcity/buildAgent/work/8c94c4c54a5058d8/src/github.com/pufferpanel/pufferd/httphandlers/oauth2.go:81 +0xacc
Jun 28 23:00:11 mercury pufferd[21561]: github.com/pufferpanel/pufferd/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc4200ea2c0)
Jun 28 23:00:11 mercury pufferd[21561]:         /home/teamcity/buildAgent/work/8c94c4c54a5058d8/src/github.com/pufferpanel/pufferd/vendor/github.com/gin-gonic/gin/context.go:104 +0x43
Jun 28 23:00:11 mercury pufferd[21561]: github.com/pufferpanel/pufferd/vendor/github.com/pufferpanel/apufferi/http/handler.Recovery.func1(0xc4200ea2c0)
Jun 28 23:00:11 mercury pufferd[21561]:         /home/teamcity/buildAgent/work/8c94c4c54a5058d8/src/github.com/pufferpanel/pufferd/vendor/github.com/pufferpanel/apufferi/http/handler/errorlogging.go:20 +0x51
Jun 28 23:00:11 mercury pufferd[21561]: github.com/pufferpanel/pufferd/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc4200ea2c0)
Jun 28 23:00:11 mercury pufferd[21561]:         /home/teamcity/buildAgent/work/8c94c4c54a5058d8/src/github.com/pufferpanel/pufferd/vendor/github.com/gin-gonic/gin/context.go:104 +0x43
Jun 28 23:00:11 mercury pufferd[21561]: github.com/pufferpanel/pufferd/vendor/github.com/gin-gonic/gin.RecoveryWithWriter.func1(0xc4200ea2c0)
Jun 28 23:00:11 mercury pufferd[21561]:         /home/teamcity/buildAgent/work/8c94c4c54a5058d8/src/github.com/pufferpanel/pufferd/vendor/github.com/gin-gonic/gin/recovery.go:45 +0x5a
Jun 28 23:00:11 mercury pufferd[21561]: github.com/pufferpanel/pufferd/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc4200ea2c0)
Jun 28 23:00:11 mercury pufferd[21561]:         /home/teamcity/buildAgent/work/8c94c4c54a5058d8/src/github.com/pufferpanel/pufferd/vendor/github.com/gin-gonic/gin/context.go:104 +0x43
Jun 28 23:00:11 mercury pufferd[21561]: github.com/pufferpanel/pufferd/vendor/github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc4200c5d40, 0xc4200ea2c0)
Jun 28 23:00:11 mercury pufferd[21561]:         /home/teamcity/buildAgent/work/8c94c4c54a5058d8/src/github.com/pufferpanel/pufferd/vendor/github.com/gin-gonic/gin/gin.go:332 +0x585
Jun 28 23:00:11 mercury pufferd[21561]: github.com/pufferpanel/pufferd/vendor/github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc4200c5d40, 0xcb63e0, 0xc4204e49a0, 0xc420212a00)
Jun 28 23:00:11 mercury pufferd[21561]:         /home/teamcity/buildAgent/work/8c94c4c54a5058d8/src/github.com/pufferpanel/pufferd/vendor/github.com/gin-gonic/gin/gin.go:296 +0x153
Jun 28 23:00:11 mercury pufferd[21561]: net/http.serverHandler.ServeHTTP(0xc420237e10, 0xcb63e0, 0xc4204e49a0, 0xc420212a00)
Jun 28 23:00:11 mercury pufferd[21561]:         /usr/local/go/src/net/http/server.go:2694 +0xbc
Jun 28 23:00:11 mercury pufferd[21561]: net/http.(*conn).serve(0xc420597360, 0xcb6ee0, 0xc420547140)
Jun 28 23:00:11 mercury pufferd[21561]:         /usr/local/go/src/net/http/server.go:1830 +0x651
Jun 28 23:00:11 mercury pufferd[21561]: created by net/http.(*Server).Serve
Jun 28 23:00:11 mercury pufferd[21561]:         /usr/local/go/src/net/http/server.go:2795 +0x27b
```

**Comment by LordRalex** [comment]
Your config.json has a URL or token which is not accepted by the panel. This is not a bug, just a bad configuration.

**Comment by nikhiljha** [comment]
Yup, that was the problem.

I do still think it's a bug though - that error message is opaque and makes it hard to figure out what's going on. In my case, the server only was running on HTTPS (443), and pufferpanel's installer defaults to HTTP (80) which wasn't working.

Perhaps the installer should be made more clear that it's defaulting to HTTP? And/or try to insert a custom/better error message when that connection fails?
