### ISSUE TITLE
Maven dependency error (spigot install)

### ISSUE THREAD

**Issue by Blamo27** [PufferPanel/PufferPanel#844]
Hello,

After a fresh install of pufferinstall, I created a spigot server (docker)

![image](https://user-images.githubusercontent.com/971712/44177370-fbfaa180-a0ed-11e8-8003-10b4f1927e64.png)

And I got this error in the console ...

```[[1;34mINFO[m] [1m------------------------------------------------------------------------[m
[[1;34mINFO[m] [1;31mBUILD FAILURE[m
[[1;34mINFO[m] [1m------------------------------------------------------------------------[m
[[1;34mINFO[m] Total time: 13.836 s
[[1;34mINFO[m] Finished at: 2018-08-15T22:43:04Z
[[1;34mINFO[m] Final Memory: 13M/756M
[[1;34mINFO[m] [1m------------------------------------------------------------------------[m
[[1;31mERROR[m] Failed to execute goal on project [36mcraftbukkit[m: [1;31mCould not resolve dependencies for project org.bukkit:craftbukkit:jar:1.12.2-R0.1-SNAPSHOT: Could not find artifact org.spigotmc:minecraft-server:jar:1.12.2-SNAPSHOT in spigotmc-public (https://hub.spigotmc.org/nexus/content/groups/public/)[m -> [1m[Help 1][m
[[1;31mERROR[m] 
[[1;31mERROR[m] To see the full stack trace of the errors, re-run Maven with the [1m-e[m switch.
[[1;31mERROR[m] Re-run Maven using the [1m-X[m switch to enable full debug logging.
[[1;31mERROR[m] 
[[1;31mERROR[m] For more information about the errors and possible solutions, please read the following articles:
[[1;31mERROR[m] [1m[Help 1][m http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
Exception in thread "main" java.lang.RuntimeException: Error running command, return status !=0: [sh, /home/pufferd/servers/273968b6-2f32-4743-a77b-011ae272e049/apache-maven-3.5.0/bin/mvn, clean, install]
	at org.spigotmc.builder.Builder.runProcess0(Builder.java:639)
	at org.spigotmc.builder.Builder.runProcess(Builder.java:597)
	at org.spigotmc.builder.Builder.main(Builder.java:473)
	at org.spigotmc.builder.Bootstrap.main(Bootstrap.java:29)
```

Can you fix that ?

**Comment by LordRalex** [comment]
This is not an issue with our panel, rather the buildtools from Spigot.
