### ISSUE TITLE
User gets error  when loading server

### ISSUE THREAD

**Issue by Nuckerr** [PufferPanel/PufferPanel#944]
So I've just installed puffer panel. I went to create a test user account without admin perms and added it to one of my servers. Instead when they load the servers page they get an error

Error:
`{ "message": "Request failed with status code 403", "name": "Error", "stack": "Error: Request failed with status code 403\n at t.exports (https://panel.nucker.me/js/chunk-vendors.25ec2db5.js:7:79339)\n at t.exports (https://panel.nucker.me/js/chunk-vendors.25ec2db5.js:20:57976)\n at XMLHttpRequest.p.onreadystatechange (https://panel.nucker.me/js/chunk-vendors.25ec2db5.js:37:44703)", "config": { "url": "/api/servers", "method": "get", "params": { "page": 1, "limit": 10 }, "headers": { "Accept": "application/json, text/plain, */*", "Authorization": "Bearer eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJzZXNzaW9uIiwiZXhwIjoxNjA0NDYyMDMwLCJpYXQiOjE2MDQ0NTg0MzAsInN1YiI6IjIiLCJwdWZmZXJwYW5lbCI6e319.OrUKHEWTaeXBWnqXqUkNq6u9C_qpTG4BKZ2cJRW-T8TEA_cuPWFPCsF-GNAj3YWPJ2TfzVco4u_t4e8s5HhC3A" }, "transformRequest": [ null ], "transformResponse": [ null ], "timeout": 0, "xsrfCookieName": "XSRF-TOKEN", "xsrfHeaderName": "X-XSRF-TOKEN", "maxContentLength": -1 } }`

Global permissions: https://gyazo.com/882476da9dc6a6cebaf6efbaa3e9c36f
Server permissions: https://gyazo.com/51440ee80bd4896b5d0e5946d2b22312

**Comment by Nuckerr** [comment]
Update You need to have `View all servers` permission
